# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://www.astronomer.io/docs/astro/cli/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

# NOTE: YOUR .GITIGNORE FOLDER WILL INCLUDE THIS FILE AFTER RUNNING `astro dev init`.
# I EXCLUDED IT FROM MINE FOR DEMONSTRATION PURPOSES ONLY
# LEAVE YOUR `airflow_settings.yaml` IN YOUR .GITIGNORE FOLDER AS IT CAN CONTAIN SENSITIVE INFO, DEPENDING ON THE PROJECT

airflow:
  pools:
    - pool_name: "api_pool"
      pool_slot: 32
      pool_description: "Pool for controlling API-heavy tasks"
    - pool_name: default_pool
      pool_slot: 128
      pool_description: Default pool
