# dbt/models/staging/schema.yml

version: 2

sources:
  - name: public # This is the schema your raw data is in
    description: "Raw data loaded from the stock market ELT pipeline."
    tables:
      - name: source_polygon_stock_bars_daily
        description: "Raw daily OHLCV data for all tickers from Polygon.io."
